apiVersion: v1
data:
  AB_INSTANCE_ADMIN_CLIENT_ID: ""
  AB_INSTANCE_ADMIN_CLIENT_SECRET: ""
  AB_INSTANCE_ADMIN_PASSWORD: ""
  AB_JWT_SIGNATURE_SECRET: ""
  AIRBYTE_DUMMY_SECRET: ZHVtbXk=
  AIRBYTE_LICENSE_KEY: ""
  AWS_ACCESS_KEY_ID: bWluaW8=
  AWS_ASSUME_ROLE_ACCESS_KEY_ID: ""
  AWS_ASSUME_ROLE_SECRET_ACCESS_KEY: ""
  AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
  BUILDER_GITHUB_AIRBYTE_PAT_TOKEN: ""
  CONNECTOR_ROLLOUT_GITHUB_AIRBYTE_PAT: ""
  CUSTOMERIO_API_KEY: ""
  DATABASE_PASSWORD: YWlyYnl0ZQ==
  DATABASE_USER: YWlyYnl0ZQ==
  DATAPLANE_CLIENT_ID: ""
  DATAPLANE_CLIENT_SECRET: ""
  INITIAL_USER_PASSWORD: ""
  KEYCLOAK_ADMIN_PASSWORD: YWlyYnl0ZTEyMw==
  KEYCLOAK_ADMIN_USER: YWlyYnl0ZUFkbWlu
  KEYCLOAK_DATABASE_PASSWORD: YWlyYnl0ZQ==
  KEYCLOAK_DATABASE_USERNAME: YWlyYnl0ZQ==
  OPENAI_API_KEY_PROJ_FAILED_SYNC_ASSISTANT: ""
  STIGG_API_KEY: ""
  TEMPORAL_CLI_TLS_CERT: ""
  TEMPORAL_CLI_TLS_KEY: ""
  TEMPORAL_CLOUD_CLIENT_CERT: ""
  TEMPORAL_CLOUD_CLIENT_KEY: ""
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  creationTimestamp: "2026-03-24T20:34:07Z"
  labels:
    airbyte: templates
    app.kubernetes.io/instance: airbyte
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: templates
    app.kubernetes.io/version: 2.0.1
    helm.sh/chart: airbyte-2.0.19
  name: airbyte-airbyte-secrets
  namespace: airbyte-v2
  resourceVersion: "101399"
  uid: f552c4bf-ec32-41d9-b420-7203b4f2e1d2
type: Opaque
