apiVersion: v1
data:
  AB_INSTANCE_ADMIN_PASSWORD: aUVMdCt1bC9sUmpFbE1hQ29ldmdlek50c0dFUXN2TGg=
  AB_JWT_SIGNATURE_SECRET: TjdGZ1QzV0d5TDRSaklzRjJqUVZRQVR5Q1pZbUMxN2s=
  INITIAL_USER_EMAIL: ZGV2b3BzQGZpdG5lc3MyMi5jb20=
  dataplane-client-id: MzZjY2M0MGMtMjEzNi00MWFlLTg0OWQtOTU0MDEwYmQxZmI5
  dataplane-client-secret: MjhmZTIxNjRmNDEwZjQwYjliYzdmZWU2ZWMzMGFkYzc2YzhhNGQ1OGJjOWYxNWJjYzQ4MjU4YjlhNDc1MTcwMQ==
  instance-admin-client-id: ZmYzYmJmNmUtMzI3OS00Y2Y0LWJmOTEtZWUwMzJlZjViOWRm
  instance-admin-client-secret: ck1sUUtidjhhd0dyTHdwTVFuWWxRU21Na0c3R2R2TGE=
  instance-admin-email: ZGV2b3BzQGZpdG5lc3MyMi5jb20=
  instance-admin-password: aUVMdCt1bC9sUmpFbE1hQ29ldmdlek50c0dFUXN2TGg=
  jwt-signature-secret: T3VYYnB4UXJNdUxvRnIwSzlSNUhRZGN4d1IxTGg5YUhibS9pbnJYQzBuST0=
kind: Secret
metadata:
  creationTimestamp: "2026-03-24T18:07:52Z"
  name: airbyte-auth-secrets
  namespace: airbyte-v2
  resourceVersion: "75532"
  uid: 9c148b59-3e91-4c0a-943c-6b2ca20916c6
type: Opaque
